---
- when: ansible_distribution == 'CentOS'
  tags: epel
  block:
    - name: yum install epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm

    - name: rpm –import RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
      rpm_key: key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
