pipeline:
  lint:
    image: kecorbin/ansible
    commands:
      - ansible-playbook site.yml --syntax-check
      - ansible-lint --exclude build/ site.yml

  configure:
    when:
        branch: test
    image: kecorbin/ansible
    environment:
      - ANSIBLE_NET_USERNAME=cisco
      - ANSIBLE_NET_PASSWORD=cisco
      - ANSIBLE_NET_AUTH=True
      - ANSIBLE_NET_AUTH_PASS=cisco
    commands:
      - env
      - ./deploy.sh --env test

  configure:
    when:
        branch: production
    image: kecorbin/ansible
    secrets: [ ANSIBLE_NET_USERNAME, ANSIBLE_NET_PASSWORD, ANSIBLE_NET_AUTH_PASS ]
    environment:
      - ANSIBLE_NET_USERNAME=$ANSIBLE_NET_USERNAME
      - ANSIBLE_NET_PASSWORD=$ANSIBLE_NET_PASSWORD
      - ANSIBLE_NET_AUTH=True
      - ANSIBLE_NET_AUTH_PASS=$ANSIBLE_NET_AUTH_PASS
    commands:
      - env
      - ./deploy.sh --env prod

  notify:
    image: hpreston/drone-spark:0.7
    secrets: [ SPARK_TOKEN, ROOMID, PERSONEMAIL ]
    roomId: $ROOMID
    when:
      status: [ success, failure ]
