pipeline:
  lint:
    image: kecorbin/ansible
    commands:
      - ansible-playbook site.yml --syntax-check
      - ansible-lint --exclude build/ site.yml

  configure:
    when:
        branch: test
    image: kecorbin/ansible
    environment:
      - ANSIBLE_NET_USERNAME=cisco
      - ANSIBLE_NET_PASSWORD=cisco
      - ANSIBLE_NET_AUTH=True
      - ANSIBLE_NET_AUTH_PASS=cisco
    commands:
      - env
      - ./deploy.sh --env test

  configure:
    when:
        branch: master
    image: kecorbin/ansible
    environment:
      - ANSIBLE_NET_USERNAME=cisco
      - ANSIBLE_NET_PASSWORD=cisco
      - ANSIBLE_NET_AUTH=True
      - ANSIBLE_NET_AUTH_PASS=cisco
    commands:
      - env
      - ./deploy.sh --env prod

  notify:
    image: hpreston/drone-spark:0.7
    secrets: [ SPARK_TOKEN, ROOMID, PERSONEMAIL ]
    roomId: $ROOMID
