stages:
  - validate
  - test
  - deploy
  - notify

lint:
  stage: validate
  image: kecorbin/ansible
  variables:
  script:
    - ansible-playbook site.yml --syntax-check
    - ansible-lint --exclude build/ site.yml

deploy_test:
  image: kecorbin/ansible
  stage: test
  script:
    - echo "Deploy to test env"
    - ansible-playbook -v --diff --inventory-file ./inventory/test.yml -- site.yml
  environment:
    name: test
  only:
  - test

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production env"
    - ansible-playbook -v --diff --inventory-file ./inventory/prod.yml -- site.yml
  environment:
    name: production
  when: manual
  only:
  - production
