stages:
  - validate
  - test
  - deploy
  - notify

lint:
  stage: validate
  image: kecorbin/ansible
  variables:
      CI_DEBUG_TRACE: "true"
  script:
    - validate.sh

deploy_test:
  image: kecorbin/ansible
  stage: test
  script:
    - echo "Deploy to test env"
  environment:
    name: test
  only:
  - test

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
  when: manual
  only:
  - master
