---

- name: Configure Core Routers
  hosts: core
  connection: local
  gather_facts: yes
  vars:
    cli:
      host: "{{ ansible_host }}"
  roles:
    - ios_xr_common
    - ios_xr_telemetry

- name: Configure Aggregation Switches
  hosts: agg
  connection: local
  gather_facts: false
  vars:
    cli:
      host: "{{ ansible_host }}"
  roles:
    - nxos_ospf_router
    - nxos_vpc_domain
    - nxos_first_hop
    - nxos_switch

- name: Configure Access Switches
  hosts: access
  connection: local
  gather_facts: false
  vars:
    cli:
      host: "{{ ansible_host }}"
  roles:
    - nxos_switch


- name: Configure WAN Routers
  hosts: wan
  connection: local
  gather_facts: false
  vars:
    cli:
      host: "{{ ansible_host }}"
  roles:
    - ios_common
