---

- name: Configure Core Routers
  hosts: core
  connection: local
  gather_facts: yes
  vars:
    cli:
      host: "{{ ansible_host }}"
  roles:
    - ios_xr_common

- name: Configure Distribution Switches
  hosts: distribution
  connection: local
  gather_facts: false
  vars:
    cli:
      host: "{{ ansible_host }}"
  roles:
    - nxos_ospf_router

- name: Configure Access Switches
  hosts: access
  connection: local
  gather_facts: false
  vars:
    cli:
      host: "{{ ansible_host }}"
  roles:
    - nxos_ospf_router
    - nxos_switch
    - nxos_vpc_domain


- name: Configure WAN Routers
  hosts: wan
  connection: local
  gather_facts: false
  vars:
    cli:
      host: "{{ ansible_host }}"
  roles:
    - ios_common
