core:
  hosts:
    core1:
      ansible_host: 10.94.242.171
    core2:
      ansible_host: 10.94.242.172
    wan9:
      ansible_host: 10.94.242.179


distribution:
  hosts:
    agg3:
      ansible_host: 10.94.242.173
    agg4:
      ansible_host: 10.94.242.174

access:
  children:
    pod56:
      hosts:
        leaf5:
          ansible_host: 10.94.242.175
        leaf6:
          ansible_host: 10.94.242.176
