test:
  children:
    core:
      hosts:
        core1:
          ansible_host: 10.94.241.171
        core2:
          ansible_host: 10.94.241.172

    wan:
      hosts:
        wan9:
          ansible_host: 10.94.241.179

    agg:
      children:
        agg34:
          hosts:
            # While it can be done, the preferred practice in Ansible is to not
            # store variables in the main inventory file.
            # http://docs.ansible.com/ansible/latest/intro_inventory.html
            agg3:
              ansible_host: 10.94.241.173
              pkl_src: 10.94.241.173
              pkl_dest: 10.94.241.174

            agg4:
              ansible_host: 10.94.241.174
              pkl_src: 10.94.241.174
              pkl_dest: 10.94.241.173

    access:
      children:
        pod56:
          hosts:
            leaf5:
              ansible_host: 10.94.241.175
            leaf6:
              ansible_host: 10.94.241.176

    branch:
      hosts:
        branch10-router10:
          ansible_host: 10.94.241.180
