---
- tags: postfix
  block:
    - when: ansible_distribution == 'Ubuntu'
      name: apt-get install postfix
      apt: name=postfix

    - when: ansible_distribution == 'CentOS'
      name: yum install postfix
      yum: name=postfix

    - name: copy main.cf /etc/postfix/
      template: src={{ distribution_name_version }}/main.cf.j2 dest=/etc/postfix/main.cf
      notify: restart postfix
