---

- name: Configure Layer 3 Interfaces
  tags: [api, nxapi, layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_interface:
    provider:
      host: "{{ ansible_host }}"
      transport: nxapi
    interface: "{{ item.interface }}"
    mode: layer3
    description: "{{ item.description }}"
    admin_state: up

- name: Configure IPv4 Address on Interface
  tags: [api, nxapi, layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_l3_interface:
    provider:
      host: "{{ ansible_host}}"
      transport: nxapi
    name: "{{ item.name }}"
    ipv4: "{{ item.ipv4 }}"
    
