---

- name: Configure Layer 3 Interfaces
  tags: [layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_interface:
    provider:
      host: "{{ ansible_host }}"
      transport: nxapi
    interface: "{{ item.interface }}"
    mode: layer3
    description: "{{ item.description }}"
    admin_state: up

- name: Configure IPv4 Address on Interface
  tags: [ip, layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_ip_interface:
    provider:
      host: "{{ ansible_host}}"
      transport: nxapi
    interface: "{{ item.interface }}"
    version: v4
    addr: "{{ item.ip }}"
    mask: "{{ item.mask }}"
