---

- name: Enable Features
  tags: features
  with_items:
    - interface-vlan
  nxos_feature:
    feature: "{{ item }}"
    state: enabled

- name: Management SVI's are present
  with_items: "{{ svi_interfaces }}"
  nxos_interface:
    interface: "{{ item.interface }}"
    state: present
    admin_state: up

- name: Management SVI IP addresses are configured
  with_items: "{{ svi_interfaces }}"
  nxos_ip_interface:
    interface: "{{ item.interface }}"
    version: v4
    addr: "{{ item.ip }}"
    mask: "{{ item.mask }}"

- name: Default Static Route is configured
  with_items: "{{ static_routes }}"
  nxos_static_route:
    provider: "{{ provider }}"
    prefix: "{{ item.prefix }}"
    next_hop: "{{ item.next_hop }}"
