---

- name: Configure VLANs
  with_items: "{{ vlans }}"
  nxos_vlan:
    provider:
      host: "{{ ansible_host }}"
      transport: nxapi
    vlan_id: "{{ item.id }}"
    name: "{{ item.name }}"

- name: Configure Trunk Ports
  with_items: "{{ trunk_ports }}"
  nxos_switchport:
    provider:
      host: "{{ ansible_host }}"
      transport: nxapi
    interface: "{{ item.interface }}"
    mode: trunk
    native_vlan: "{{ item.native_vlan }}"
    trunk_allowed_vlans: "{{ item.allowed_vlans }}"

- name: Configure Access Ports
  with_items: "{{ access_ports }}"
  nxos_switchport:
    provider:
      host: "{{ ansible_host }}"
      transport: nxapi
    interface: "{{ item.interface }}"
    mode: access
    access_vlan: "{{ item.access_vlan }}"

- name: Set spanning tree port type edge
  with_items: "{{ access_ports }}"
  when: item.type == 'edge'
  nxos_config:
    provider:
      host: "{{ ansible_host }}"
      transport: nxapi
    lines: spanning-tree port type edge
    parents: "{{ item.interface }}"
