---
#
# This is the one file that violates my rule of "don't just throw a bunch of
# stuff into a role." These are all really useful tools, with single line
# installs
#

- tags: debug-tools
  block:
    - when: ansible_distribution == 'Ubuntu'
      name: apt-get install <cool-stuff>
      apt: name={{ item }}
      with_items:
        - curl
        - htop
        - iotop
        - jq
        - mailutils
        - nload
        - nmon
        - rsync
        - screen
        - sysstat
        - tcpdump
        - traceroute
        - tshark
        - unzip
        - vim
        - wget

    - when: ansible_distribution == 'CentOS'
      name: yum install <cool-stuff>
      yum: name={{ item }}
      with_items:
        - curl
        - htop
        - iotop
        - jq
        - lsof
        - mailx
        - nload
        - rsync
        - screen
        - sysstat
        - tcpdump
        - traceroute
        - wireshark
        - wget
