---

- name: Generate SSH Key
  telnet:
    user: cisco
    password: cisco
    login_prompt: "Username: "
    prompts:
      - "[>|#]"
      - ": "
    command:
      - crypto key generate rsa
      - "2048"
      - term len 0

- name: Validate Key Generation
  telnet:
    user: cisco
    password: cisco
    login_prompt: "Username: "
    prompts:
      - "[>|#]"
    command:
      - 'show crypto key mypubkey rsa'


- name: "Applying Common IOS Template"
  iosxr_config:
    provider: "{{ cli }}"
    src: "xr_base_template.j2"

- name: Enable XML Agent
  iosxr_config:
    provider: "{{ cli }}"
    lines:
      - xml agent ssl
      - xml agent tty
