---

- name: Generate SSH Key
  telnet:
    user: cisco
    password: cisco
    login_prompt: "Username: "
    prompts:
      - "[>|#]"
      - ": "
    command:
      - crypto key generate rsa
      - "2048"
      - term len 0

- name: "Applying Common IOS Template"
  iosxr_config:
    provider: "{{ cli }}"
    src: "xr_base_template.j2"
