---

- name: Generate SSH Key
  telnet:
    user: cisco
    password: cisco
    login_prompt: "Username: "
    prompts:
      - "[>|#]"
      - ": "
    command:
      - crypto key generate rsa
      - "2048"
      - term len 0

# Doing crypto stuff can take a minute..
- name: Pausing to ensure ssh is enabled after crypto generation
  pause:
    minutes: 1

- name: "Applying Common IOS Template"
  iosxr_config:
    provider: "{{ cli }}"
    src: "xr_base_template.j2"

- name: Enable XML Agent
  iosxr_config:
    provider: "{{ cli }}"
    lines:
      - xml agent ssl
      - xml agent tty
