hostname: agg3
device_type: nxos
mgmt_ip: 10.94.241.167/24
mgmt_default_gw: 10.94.241.161

features:
  - telnet

domain_name: "netdevops.is.cool"


l3_interfaces:

  - name: Loopback0
    ipv4: 192.168.255.3/32
    description: router-id

  - name: Ethernet1/1
    description: "to-core1-gig3"
    ipv4: 10.0.0.9/30

  - name: Ethernet1/2
    description: "to-core2-gig3"
    ipv4: 10.0.0.21/30

  - name: Ethernet1/3
    description: "to-agg4-gig3"
    ipv4: 10.0.0.33/30

  - name: Ethernet1/4
    description: "to-agg4-gig4"
    ipv4: 10.0.0.37/30

  - name: Ethernet1/5
    description: "to-leaf5-gig3"
    ipv4: 10.0.0.41/30

  - name: Ethernet1/6
    description: "to-leaf6-gig3"
    ipv4: 10.0.0.45/30

ospf:
  process_id: 1
  networks:
    - interface: Ethernet1/1
      area: 0
    - interface: Ethernet1/2
      area: 0
    - interface: Ethernet1/3
      area: 0
    - interface: Ethernet1/4
      area: 0
    - interface: Ethernet1/5
      area: 56
    - interface: Ethernet1/6
      area: 56
    - interface: Loopback0
      area: 0
