hostname: agg4
device_type: nxos

features:
  - telnet

domain_name: "byron.is.cool"

l3_interfaces:

  - interface: Loopback0
    ip: 192.168.255.4
    description: router-id
    mask: 32

  - interface: Ethernet1/1
    description: "to-core1-gig4"
    ip: 10.0.0.13
    mask: 30

  - interface: Ethernet1/2
    description: "to-core2-gig4"
    ip: 10.0.0.25
    mask: 30

svi_interfaces:
  - interface: vlan34
    description: inband-mgmt
    ip: 192.168.34.44
    mask: 24
  - interface: vlan7
    description: servervlan7
    ip: 192.168.7.4
    mask: 24
  - interface: vlan8
    description: servervlan8
    ip: 192.168.8.4
    mask: 24
  - interface: vlan35
    ip: 192.168.35.4
    mask: 24
    description: vlan35
