device_type: csr

vrfs:
  - Mgmt-intf

bgp:
  as_number: 1
  router_id: 192.168.255.10
  neighbors:
    192.168.255.9:
      remote_as: 1
      description: wan9
      update_source: Loopback0
  networks:
    192.168.255.10:
      mask: 255.255.255.255

ospf:
    process: 1
    networks:
      10.9.10.0:
        wildcard_mask: 0.0.0.255
        area: 0
      192.168.10.0:
        wildcard_mask: 0.0.0.255
        area: 0

    passive_interfaces:
      - Loopback0

mgmt_vrf: Mgmt-intf

domain_name: "netdevops.is.cool"

loopbacks:
  Loopback0:
    description: "router id"
    ip: 192.168.255.10
    mask: 255.255.255.255


interfaces:

  GigabitEthernet2:
    description: "to-wan9"
    ip: 10.9.10.10
    mask: 255.255.255.0
    ospf:
      cost: 1

  GigabitEthernet3:
    description: "to-agg3-gig1"
    ip: 192.168.10.1
    mask: 255.255.255.0
