device_type: csr

vrfs:
  - Mgmt-intf

bgp:
  as_number: 123
  router_id: 192.168.255.10
  neighbors:
    - peer_ip: 192.168.255.9
      remote_as: 123
      description: wan9
      update_source: Loopback0
  networks:
    - network: 10.0.10.0
      mask: 255.255.255.0

ospf:
    process: 1
    networks:
      10.0.109.0:
        wildcard_mask: 0.0.0.255
        area: 0
      192.168.10.0:
        wildcard_mask: 0.0.0.255
        area: 0
      192.168.255.10:
        wildcard_mask: 0.0.0.0
        area: 0
      10.0.100.0:
        wildcard_mask: 0.0.0.255
        area: 0

    passive_interfaces:
      - Loopback0

mgmt_vrf: Mgmt-intf

domain_name: "netdevops.is.cool"

loopbacks:
  Loopback0:
    description: "router id"
    ip: 192.168.255.10
    mask: 255.255.255.255
  Loopback1:
    description: "bgp network"
    ip: 10.0.10.10
    mask: 255.255.255.0

interfaces:

  GigabitEthernet2:
    description: "to-wan9"
    ip: 10.0.109.10
    mask: 255.255.255.0
    ospf:
      cost: 1

  GigabitEthernet3:
    description: "to-agg3-gig1"
    ip: 192.168.10.1
    mask: 255.255.255.0

  GigabitEthernet4:
    description: "tgen10-4"
    ip: 10.0.100.1
    mask: 255.255.255.0
